# Site settings
title: 如是我闻
SEOTitle: 如是我闻 | 沐杰的文章
header-img: img/home-bg-dx.jpg
email: harryfhliu@outlook.com
description: "沐杰的文章"
keyword: "沐杰, harryfhliu, 刘富华, 地热, 小说, 敦煌遗影"
url: "http://harryliu.cn"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/harryfhliu/harryfhliu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "巧言令色！"
sidebar-avatar: /img/about-harry-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     harryfhliu
zhihu_username:     harryfhliu
github_username:    harryfhliu
facebook_username:  harryfhliu
jianshu_username:   a188c2bce504
twitter_username:   harryfhliu




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: harryfhliu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 61a14eeff60953377982                            #生成的clientID
  clientSecret: 0b0675a20a85b45b203ee7e0099d38432076eb04    #生成的clientSecret
  repo: harryfhliu.github.io    #仓库名称
  owner: harryfhliu    #github用户名
  admin: harryfhliu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: harryfhliu.cn                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 5              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "IGA",
        href: "https://www.geothermal-energy.org/"
    },{
        title: "REW",
        href: "https://www.renewableenergyworld.com/index.html"
    },{
        title: "GRC",
        href: "https://geothermal.org/home.html"
    },{
        title: "NEA",
        href: "https://nea.is/"
    },{
        title: "DOE",
        href: "https://www.energy.gov/"
    }
]

theme: jekyll-theme-slate
